server {
    listen 80;
    server_name _;

    # Portal Inicial AMT-HUB
    location / {
        root /usr/share/nginx/html/portal;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # pfViewer
    location /pfviewer/ {
        alias /usr/share/nginx/html/pfviewer/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # SIGHE - Interface Frontend (HTML, CSS, JS)
    location /sighe/ {
        alias /usr/share/nginx/html/sighe-frontend/;
        index index.html;
        try_files $uri $uri/ /sighe/index.html;
    }

    # API do Portal AMT-HUB (Servidor Python - Apps e Escalas)
    location /api/apps {
        proxy_pass http://172.17.0.1:8000/api/apps;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/escala/ {
        proxy_pass http://172.17.0.1:8000/api/escala/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10M;
    }

    # SIGHE - Backend API (Node.js)
    location /api/ {
        proxy_pass http://amt-sighe-api:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Gerador de Senhas
    location /passgen/ {
        alias /usr/share/nginx/html/passgen/;
        index index.html;
        try_files $uri $uri/ /passgen/index.html;
    }
    
}